export const BLOG_ACTIONS = {
    // Get all blogs
    GET_ALL_BLOGS_REQUEST: 'GET_ALL_BLOGS_REQUEST',
    GET_ALL_BLOGS_SUCCESS: 'GET_ALL_BLOGS_SUCCESS',
    GET_ALL_BLOGS_FAILURE: 'GET_ALL_BLOGS_FAILURE',
    
    // Get single blog
    GET_BLOG_REQUEST: 'GET_BLOG_REQUEST',
    GET_BLOG_SUCCESS: 'GET_BLOG_SUCCESS',
    GET_BLOG_FAILURE: 'GET_BLOG_FAILURE',
    
    // Create blog
    CREATE_BLOG_REQUEST: 'CREATE_BLOG_REQUEST',
    CREATE_BLOG_SUCCESS: 'CREATE_BLOG_SUCCESS',
    CREATE_BLOG_FAILURE: 'CREATE_BLOG_FAILURE',
    
    // Update blog
    UPDATE_BLOG_REQUEST: 'UPDATE_BLOG_REQUEST',
    UPDATE_BLOG_SUCCESS: 'UPDATE_BLOG_SUCCESS',
    UPDATE_BLOG_FAILURE: 'UPDATE_BLOG_FAILURE',
    
    // Delete blog
    DELETE_BLOG_REQUEST: 'DELETE_BLOG_REQUEST',
    DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILURE: 'DELETE_BLOG_FAILURE',
  };